services:
  crawler:
    build: .
    container_name: crawler
    ports:
      - "8080:8080"
    environment:
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - MONGO_URL=mongodb://lazuli:x1RWo6cqFtHiaAHce5HB@mongo:27017/admin
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_USERNAME=lazuli
      - MONGO_INITDB_PASSWORD=x1RWo6cqFtHiaAHce5HB
      - MONGO_INITDB_AUTH=root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
